spring.application.name=spctn



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

server.port=8081

jwt.expiration=86400000
jwt.refresh.expiration=604800000

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB




spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/spacesongs}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Khalid147369}

jwt.secret=${JWT_SECRET:5d3c8d2e8d9f7c4b6a1f2e3d4c5b6a7f8e9d0c1b2a3d4e5f6a7b8c9d0e1f2a3}

cloudinary.cloud-name=${CLOUDINARY_NAME:dwxkdvgxk}
cloudinary.api-key=${CLOUDINARY_API_KEY:222754938185799}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:U1So-edmPp9gBa-HJGn-ld9tNH0}
