version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: mysql-spacesongs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spacesongs
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: spacesongs-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
	environment:
		
		SPRING_PROFILES_ACTIVE: local
		
	      DB_URL: ${DB_URL}
	      DB_USERNAME: ${DB_USERNAME}
	      DB_PASSWORD: ${DB_PASSWORD}
	      JWT_SECRET: ${JWT_SECRET}
	      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
	      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
	      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
	      GEMINI_API_KEY: ${GEMINI_API_KEY}
	      GEMINI_API_URL: ${GEMINI_API_URL}
	      JWT_EXPIRATION: ${JWT_EXPIRATION}
	      JWT_REFRESH_EXPIRATION: ${JWT_REFRESH_EXPIRATION}
	      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

volumes:
  mysql_data: