services:
  mysql:
    image: mysql:8.4
    container_name: mysql-spacesongs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spacesongs
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: spacesongs-api
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/spacesongs
      DB_USERNAME: root
      DB_PASSWORD: root
      JWT_SECRET: 5d3c8d2e8d9f7c4b6a1f2e3d4c5b6a7f8e9d0c1b2a3d4e5f6a7b8c9d0e1f2a3
      CLOUDINARY_NAME: dwxkdvgxk
      CLOUDINARY_API_KEY: 222754938185799
      CLOUDINARY_API_SECRET: U1So-edmPp9gBa-HJGn-ld9tNH0

volumes:
  mysql_data: